# Generated by Django 5.2.14 on 2026-05-07 16:35

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_externo', models.CharField(default='0', max_length=255, primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FechaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_dia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fechas_eventos',
                'managed': False,
            },
        ),
    ]
