# Generated by Django 5.2.13 on 2026-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_dia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fechas_eventos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'managed': False},
        ),
    ]
