# Generated by Django 6.0.5 on 2026-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovamos',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariovamos',
            name='categorias_preferidas',
            field=models.JSONField(blank=True, default=list, help_text="Ej: ['Deportiva', 'Cultura', 'Feria']"),
        ),
        migrations.AddField(
            model_name='usuariovamos',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuariovamos',
            name='notificaciones_activas',
            field=models.BooleanField(default=True, help_text='El usuario acepta recibir notificaciones push'),
        ),
        migrations.AddField(
            model_name='usuariovamos',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
