# Generated by Django 5.2.13 on 2026-05-04 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('CASA', 'En casa'), ('CAMINO', 'En camino'), ('EVENTO', 'En evento'), ('CANCELADO', 'Cancelado')], default='CASA', max_length=15)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'evento_id')},
            },
        ),
    ]
