# Generated by Django 5.2.14 on 2026-05-20 18:42

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(max_length=255)),
                ('invite_code', models.CharField(default=usuarios.models.generar_invite_code, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vamos_grupos',
            },
        ),
        migrations.CreateModel(
            name='EventoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('saved', 'Me Interesa'), ('confirmed', 'Vamos / Confirmado')], max_length=20)),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vamos_eventos_guardados',
                'unique_together': {('usuario', 'evento_id')},
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('llegue', 'Llegué'), ('cancelado', 'Cancelado'), ('esperando', 'Esperando fuera')], default='pendiente', max_length=20)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('fecha_estado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='usuarios.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vamos_miembros_grupo',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
    ]
