# Generated by Django 5.2.13 on 2026-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_asistenciaevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaevento',
            name='evento_id',
            field=models.CharField(max_length=255),
        ),
    ]
