# Generated by Django 6.0.5 on 2026-05-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariovamos_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariovamos',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuariovamos',
            table='usuarios_vamos',
        ),
    ]
