# Generated by Django 5.2.14 on 2026-05-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_grupo_eventoguardado_miembrogrupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsistenciaEvento',
        ),
    ]
